# Generated by Django 5.0.3 on 2024-04-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact_alter_product_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='contact_desc',
        ),
    ]
